package pi.vocal.management.returncodes;

public enum ErrorCode {

	// account creation errors
	PASSWORD_MISSING,
	PASSWORD_TOO_SHORT,
	PASSWORDS_DONT_MATCH,
	FIRSTNAME_MISSING,
	LASTNAME_MISSING,
	GRADE_MISSING,
	SCHOOL_LOCATION_MISSING,
	EMAIL_MISSING,
	EMAIL_ALREADY_IN_USE,
	EMAIL_INVALID,
	SESSION_INVALID,
	
	// event creation errors
	TITLE_MISSING,
	STARTDATE_MISSING,
	ENDDATE_MISSING,
	EVENT_TYPE_MISSING,
	STARTDATE_AFTER_ENDDATE,
	NO_ATTENDANCE_GRADE_SELECTED,
	INVALID_USER_PERMISSIONS,
	
	// misc
	INTERNAL_ERROR,
	INVALID_USER_ID,
	INVALID_EVENT_ID,
	
	// login errors
	AUTHENTICATION_FAILED;
}
