package pi.vocal.management.returncodes;

public enum SuccessCode {

	// change user codes
	PASSWORD_CHANGED,
	FIRSTNAME_CHANGED,
	LASTNAME_CHANGED,
	GRADE_CHANGED,
	SCHOOL_LOCATION_CHANGED,
	
	//change event codes
	TITLE_CHANGED,
	DESCRIPTION_CHANGED,
//	STARTDATE_CHANGED, // change to period?
//	ENDDATE_CHANGED,
	PERIOD_CHANGED,
	EVENTTYPE_CHANGED,
	ATTENDANCE_GRADES_CHANGED;
}
